Tweaks
component-driven/component-driven-development pull request #85
Opened 2020-05-24 19:15 UTC by sapegin

2020-05-24 20:06 UTC, okonet requested changes
I saw just one typo but other than that that's some bad ass job you've done! 👏

2020-05-24 20:06 UTC, okonet commented on src/exercises/2-2-Compound_components/Readme.md
> +Monolithic components with many props to suport many different use cases are hard to learn and use, and they make impossible states possible — not all combinations of props make sense. They are also
```suggestion
Monolithic components with many props to support many different use cases are hard to learn and use, and they make impossible states possible — not all combinations of props make sense. They are also harder to maintain. Even with many props, the flexibility is still limited. For example, in our Prompt component, there’s no way to change the submit button label.
```

2020-05-25 07:46 UTC, sapegin commented
@okonet Going to approve it? 🌵

2020-05-25 07:48 UTC, okonet approved these changes

2020-05-25 07:49 UTC, merged